# Generated by Django 5.0.1 on 2024-01-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('text_reviews_count', models.IntegerField()),
                ('ratings_count', models.IntegerField()),
                ('average_rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_without_series', models.CharField(max_length=255)),
                ('book_id', models.IntegerField()),
                ('work_id', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('text_reviews_count', models.IntegerField()),
                ('ratings_count', models.IntegerField()),
                ('country_code', models.CharField(max_length=255)),
                ('language_code', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('num_pages', models.IntegerField()),
                ('link', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('publication_day', models.IntegerField()),
                ('publication_month', models.IntegerField()),
                ('publication_year', models.IntegerField()),
                ('similar_books', models.CharField(max_length=255)),
                ('edition_information', models.CharField(max_length=255)),
                ('series', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=255)),
                ('isbn13', models.CharField(max_length=255)),
                ('format', models.CharField(max_length=255)),
                ('asin', models.CharField(max_length=255)),
                ('kindle_asin', models.CharField(max_length=255)),
                ('is_ebook', models.BooleanField()),
            ],
        ),
    ]
